version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "49008:80"
    volumes:
      - .:/var/www/axeta-test
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    restart: always
    links:
      - php

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/axeta-test
    restart: always
    links:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:latest
    ports:
      - "49009:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  rabbitmq:
    image: rabbitmq:3.11.22-management
    hostname: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
